log:
  level: INFO
  filePath: "/var/log/traefik/traefik.log"

api:
  insecure: true

providers:
  docker:
    exposedByDefault: false
    network: gateway_net
    endpoint: "unix:///var/run/docker.sock"

entryPoints:
  api-t:
    address: ":8000"