services:
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    restart: on-failure:5
    volumes:
      - minio_data:/minio_data
    command: minio server /minio_data --console-address ":9001"
    # command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio.rule=PathPrefix(`/document-service/minio`)"
      - "traefik.http.routers.minio.entrypoints=api-t"
      - "traefik.http.middlewares.minio-stripper.stripprefix.prefixes=/document-service/minio"
      - "traefik.http.routers.minio.middlewares=minio-stripper"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"
    networks:
      - cloudflare_tunnel_net
      - gateway_net
  

volumes:
  minio_data:

networks:
  gateway_net:
    external: true
  cloudflare_tunnel_net:
    external: true